# Generated by Django 3.1.6 on 2021-04-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(default='0123456789', max_length=12)),
                ('user2', models.CharField(default='9876543210', max_length=12)),
                ('user2Name', models.CharField(default='Name', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='0123456789', max_length=12)),
                ('reciever', models.CharField(default='9876543210', max_length=12)),
                ('message', models.CharField(default='message', max_length=500)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='email', max_length=200)),
                ('pid', models.CharField(default='0', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='email', max_length=200)),
                ('name', models.CharField(default='name', max_length=200)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('password', models.CharField(default='1234', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('email', models.CharField(default='email', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=200)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('password', models.CharField(default='1234', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobiletype', models.CharField(default='mobiletype', max_length=100)),
                ('brand', models.CharField(default='brand', max_length=100)),
                ('model', models.CharField(default='model', max_length=100)),
                ('year', models.IntegerField(default='year')),
                ('features', models.CharField(default='features', max_length=200)),
                ('details', models.CharField(default='details', max_length=200)),
                ('image', models.CharField(default='image', max_length=10000000)),
                ('price', models.IntegerField(default='0')),
                ('location', models.CharField(default='location', max_length=200)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('laptoptype', models.CharField(default='laptopType', max_length=100)),
                ('brand', models.CharField(default='brand', max_length=100)),
                ('model', models.CharField(default='model', max_length=100)),
                ('year', models.IntegerField(default='year')),
                ('features', models.CharField(default='features', max_length=200)),
                ('details', models.CharField(default='details', max_length=200)),
                ('image', models.CharField(default='image', max_length=10000000)),
                ('price', models.IntegerField(default='0')),
                ('location', models.CharField(default='location', max_length=200)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('furnituretype', models.CharField(default='furnitureType', max_length=100)),
                ('features', models.CharField(default='features', max_length=200)),
                ('details', models.CharField(default='details', max_length=200)),
                ('image', models.CharField(default='image', max_length=10000000)),
                ('price', models.IntegerField(default='0')),
                ('location', models.CharField(default='location', max_length=200)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='brand', max_length=100)),
                ('year_of_registration', models.IntegerField(default='year')),
                ('model', models.CharField(default='model', max_length=100)),
                ('variant', models.CharField(default='variant', max_length=100)),
                ('state_of_registration', models.CharField(default='state', max_length=100)),
                ('no_of_owners', models.CharField(default='owners', max_length=40)),
                ('kms_driven', models.CharField(default='kms_driven', max_length=200)),
                ('fuel', models.CharField(default='fuel', max_length=100)),
                ('transmission', models.CharField(default='transmission', max_length=100)),
                ('features', models.CharField(default='features', max_length=200)),
                ('details', models.CharField(default='details', max_length=200)),
                ('image', models.CharField(default='image', max_length=10000000)),
                ('price', models.IntegerField(default='0')),
                ('location', models.CharField(default='location', max_length=200)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('biketype', models.CharField(default='biketype', max_length=100)),
                ('brand', models.CharField(default='brand', max_length=100)),
                ('model', models.CharField(default='model', max_length=100)),
                ('year', models.IntegerField(default='year')),
                ('kms_driven', models.CharField(default='kms_driven', max_length=200)),
                ('features', models.CharField(default='features', max_length=200)),
                ('details', models.CharField(default='details', max_length=200)),
                ('image', models.CharField(default='image', max_length=10000000)),
                ('price', models.IntegerField(default='0')),
                ('location', models.CharField(default='location', max_length=200)),
                ('name', models.CharField(default='name', max_length=100)),
                ('phone', models.CharField(default='phone', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.signup')),
            ],
        ),
    ]
