# Generated by Django 3.1.6 on 2021-04-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.CharField(default='image', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(default='image', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.CharField(default='image', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.CharField(default='image', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.CharField(default='image', max_length=1000000),
        ),
    ]
